config/routes.rb
MoMaApp::Application.routes.draw do

    resources :paintings
    resources :artists
    

end

app/models/artist.rb
class Artist < ActiveRecord::Base
   attr_accessible :name, :dob, :nationality, :period, :image

   has_many :paintings


   # def early_years_paintings
   #  year = self.dob + 20.years
   #  self.paintings.
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  attr_accessible :name
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :title, :year, :medium, :style, :image, :artist_id

  belongs_to :artist

  validates_presence_of :year, :artist
  validates_uniqueness_of :title

  validate :ian

  def ian
    if self.year.to_i > Time.now.year
      errors.add(:year, "Year is in the future")
    end 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.create(params[:id])
    render :show #@artist
  end

  def show
    @artist = Artist.find(params[])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update_attributes(params[:artist])
      render :show
    else
      render :edit
    end
  end

  def destroy
    artist = Artist.find(params[:id])
    artist.delete
    redirect_to(artists_path)
  end

end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

  def new #get
    @painting = Painting.new
  end

  def create #post
		p = Painting.new(params[:painting])
		if p.save
			redirect_to p
		else
			render :new
		end
	end

  def index #get read multiple objects
    @paintings = Painting.all
  end

  def show #get read one objectexit
    @painting= Painting.find(params[:id])
  end

  def edit #get
  	@painting = Painting.find(params[:id])

  end

  def update #post
  	@painting = Painting(params[:id])
  	if @painting.update_attributes(params[:painting])
  		redirect_to painting_path
  	end
  end

  def destroy #delete
  	@painting = Painting.find(params[:id])
  	if @painting.destroy
  		redirect_to paintings_path
  	else
  		flash[:notice] = "Didn't work"
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_form.html.erb
<h1>Add a new Artist to our Collection</h1>

<%= form_for @artist do |f| %>
  <%= f.label :artist_id %>
  <%= f.select :artist_id, Artist.all.map{|artist| [artist.name,artist.id]}, :include_blank => true, :prompt => "Pick Artist!" %>
  
  <br>
  <%= f.text_field :name %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :dob %>
  <%= f.label :dob %>
  <br>
  <%= f.text_field :nationality %>
  <%= f.label :nationality %>
  <br>
  <%= f.text_field :period %>
  <%= f.label :period %>
  <br>
  <%= f.text_field :image %>
  <%= f.label :image %>
  <br>
  <%= f.submit %>
<% end %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render :partial => 'form' %>



<h1>Add a new Artist to our Collection</h1>

<%= form_for @artist do |f| %>
  <%= f.label :artist_id %>
  <%= f.select :artist_id, Artist.all.map{|artist| [artist.name,artist.id]}, :include_blank => true, :prompt => "Pick Artist!" %>
  
  <br>
  <%= f.text_field :name %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :dob %>
  <%= f.label :dob %>
  <br>
  <%= f.text_field :nationality %>
  <%= f.label :nationality %>
  <br>
  <%= f.text_field :period %>
  <%= f.label :period %>
  <br>
  <%= f.text_field :image %>
  <%= f.label :image %>
  <br>
  <%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<ul>
	<li><%= link_to @artist.name, @artist %></li>
	<li><%= @artist.nationality %></li>
	<li><%= @artist.dob.strftime %></li>
	<li><%= @artist.period%></li>
	<li><%= image_tag(@artist.image) %></li>
</ul>

<% @artist.paintings.each do |painting| %>
<ul>
	<li><%= link_to painting.title, painting%></li>
	<li><%= painting.year%></li>
	<li><%= painting.medium%></li>
	<li><%= painting.style%></li>
	<li><%= image_tag(painting.image)%></li>
</ul>
end

<%= button_to 'Delete', artist_path(@artist.id), :method => :delete %>
<%= link_to 'Edit', edit_artist_path(@artist) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MoMaApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paintings/edit.html.erb
<%= form_for @painting do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
<br>
	<%= f.label :year %>
	<%= f.text_field :year %>
<br>
	<%= f.label :medium %>
	<%= f.text_field :medium %>
<br>
	<%= f.label :style %>
	<%= f.text_field :style %>
<br>
	<%= f.submit "Submit" %>
	<% end%>

app/views/paintings/index.html.erb
<h1>These are our paintings:</h1>

	<% @paintings.each do |painting| %>
		<ol>
		<%= painting.title %>
		</ol> 
		<ol>
			<img src="<%=painting.image%>" ></ol>
			<br>
			<%= link_to "Edit/Update", edit_painting_path(painting.id)%>
			<%= button_to "DESTROY", painting, :method => :delete  %>
		<% end%>

app/views/paintings/new.html.erb
<h1> Add a new painting </h1>

<%= form_for @painting do |f| %>
  <%= f.label :artist_id %>
  <%= f.select :artist_id, Artist.all.map{|artist| [artist.name,artist.id]}, :include_blank => true, :prompt => "Pick Artist!" %>
  <br>
  <%= f.text_field :title %>
  <%= f.label :title %>
  <br>
  <%= f.text_field :year %>
  <%= f.label :year %>
  <br>
  <%= f.text_field :medium %>
  <%= f.label :medium %>
  <br>
  <%= f.text_field :style %>
  <%= f.label :style %>
  <br>
  <%= f.text_field :image %>
  <%= f.label :image %>
  <br>
  <%= f.submit %>
  
<% end %>

app/views/paintings/show.html.erb
<h3>This Is Your New Submission Pending Approval</h3>


<%= @painting.title %><br>
<%= @painting.year %><br>
<%= @painting.medium %><br>
<%= @painting.style %><br>
<%= link_to "edit", edit_painting_path(@painting.id)%>
<img src="<%=@painting.image%>" >